name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile.dev --tag lburja/docker-react

      - name: Run tests
        run: docker run -e CI=true lburja/docker-react npm run test
